name: Data Update

on:
  workflow_dispatch:
  schedule:
  - cron:  '11 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3.5.3
    - name: Install just
      uses: extractions/setup-just@v1
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Update databases
      env:
        GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
        POCKET_USERNAME: ${{ secrets.POCKET_USERNAME }}
        POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
        MASTODON_DOMAIN: ${{ secrets.MASTODON_DOMAIN }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      run: just --justfile data/Justfile remote
    - name: Commit updates
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Data Update
        file_pattern: 'data/*.db'
